{% set name = "lancedb" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lancedb/lancedb/archive/v{{ version }}.tar.gz
  sha256: 97d5d6f3066bde99ec636e1f3f422cacf3fd383a363a55849adaf4a004d4ea76

build:
  entry_points:
    - lancedb = lancedb.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - maturin >=1.4
    - pip
  run:
    - python >=3.8
    - deprecation
    - pylance ==0.13.0
    - ratelimiter >=1.0,<2.dev0
    - requests >=2.31.0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - packaging
    - cachetools
    - overrides >=0.7

test:
  imports:
    - lancedb
  commands:
    - pip check
    - lancedb --help
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - mediocretech
    - jan-janssen
