{% set name = "lancedb" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lancedb-{{ version }}.tar.gz
  sha256: 034ef65d1456ca7f0f9dfc33c93d7cbfa893b45411d218258f1c01a1c069bdbf

build:
  entry_points:
    - lancedb = lancedb.cli.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - deprecation
    - pylance ==0.9.15
    - ratelimiter >=1.0,<2.dev0
    - retry >=0.9.2
    - tqdm >=4.27.0
    - pydantic >=1.10
    - attrs >=21.3.0
    - semver >=3.0
    - cachetools
    - pyyaml >=6.0
    - click >=8.1.7
    - requests >=2.31.0
    - overrides >=0.7

test:
  imports:
    - lancedb
  commands:
    - pip check
    - lancedb --help
  requires:
    - pip

about:
  home: https://github.com/lancedb/lancedb
  summary: Developer-friendly, serverless vector database for AI applications
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
